package main

import (
	"fmt"
	"strings"
)

// ── Emitter ───────────────────────────────────────────────────────────────────

type Emitter struct {
	sb          strings.Builder
	indent      int
	file        string
	errors      []TranspileError
	testMethods []string // collected @test methods: "ClassName::MethodName"
}

func NewEmitter(file string) *Emitter {
	return &Emitter{file: file}
}

func (e *Emitter) Emit(cu *CompilationUnit) (string, []TranspileError) {
	e.writePreamble()
	for _, u := range cu.Usings {
		e.emitUsing(u)
	}
	e.writeln("")
	for _, ns := range cu.Namespaces {
		e.emitNamespace(ns)
	}
	for _, d := range cu.Members {
		e.emitDecl(d, "")
	}
	return e.sb.String(), e.errors
}

func (e *Emitter) writePreamble() {
	e.writeln("// Auto-generated by cstranspiler — do not edit manually")
	e.writeln("#include <string>")
	e.writeln("#include <vector>")
	e.writeln("#include <stdexcept>")
	e.writeln("#include <iostream>")
	e.writeln("#include <memory>")
	e.writeln("#include <typeinfo>")
	e.writeln("#include <cstdint>")
	e.writeln("#include <algorithm>")
	e.writeln("")
	// Type aliases for C# primitives
	e.writeln("// C# primitive type aliases")
	e.writeln("using int8   = int8_t;")
	e.writeln("using uint8  = uint8_t;")
	e.writeln("using int16  = int16_t;")
	e.writeln("using uint16 = uint16_t;")
	e.writeln("using int32  = int32_t;")
	e.writeln("using uint32 = uint32_t;")
	e.writeln("using int64  = int64_t;")
	e.writeln("using uint64 = uint64_t;")
	e.writeln("using sbyte  = int8_t;")
	e.writeln("using byte   = uint8_t;")
	e.writeln("using ushort = uint16_t;")
	e.writeln("using uint   = uint32_t;")
	e.writeln("using ulong  = uint64_t;")
	e.writeln("using String = std::string;")
	e.writeln("")
	// typeof helper
	e.writeln("// typeof() helper")
	e.writeln("template<typename T> inline std::string typeof_name() { return typeid(T).name(); }")
	e.writeln("template<typename T> inline std::string typeof_name(const T&) { return typeid(T).name(); }")
	e.writeln("")
	// Null literal
	e.writeln("#define null nullptr")
	e.writeln("")
}

func (e *Emitter) emitUsing(u *UsingDecl) {
	// Map common C# using -> C++ include or namespace
	path := nsPath(u.Path)
	switch path {
	case "System":
		// already included
	case "System.Collections.Generic":
		e.writeln("#include <map>")
		e.writeln("#include <unordered_map>")
		e.writeln("#include <list>")
	case "System.IO":
		e.writeln("#include <fstream>")
		e.writeln("#include <sstream>")
	case "System.Math":
		e.writeln("#include <cmath>")
	default:
		e.writeln(fmt.Sprintf("// using %s; (skipped — no C++ equivalent)", path))
	}
}

func (e *Emitter) emitNamespace(ns *NamespaceDecl) {
	name := nsPath(ns.Path)
	// Replace dots with :: for nested namespaces
	cppName := strings.ReplaceAll(name, ".", "::")
	// Open
	parts := strings.Split(cppName, "::")
	for _, p := range parts {
		e.writef("namespace %s {\n", p)
		e.indent++
	}
	e.writeln("")
	for _, d := range ns.Members {
		if nested, ok := d.(*NamespaceDecl); ok {
			e.emitNamespace(nested)
		} else {
			e.emitDecl(d, "")
		}
	}
	// Close
	for i := len(parts) - 1; i >= 0; i-- {
		e.indent--
		e.writef("} // namespace %s\n", parts[i])
	}
	e.writeln("")
}

func (e *Emitter) emitDecl(d Decl, nsPrefix string) {
	switch v := d.(type) {
	case *ClassDecl:
		e.emitClass(v)
	case *StructDecl:
		e.emitStruct(v)
	case *InterfaceDecl:
		e.emitInterface(v)
	case *EnumDecl:
		e.emitEnum(v)
	case *FieldDecl:
		e.emitTopField(v)
	case *MethodDecl:
		e.emitTopMethod(v)
	}
}

// ── Class emission ────────────────────────────────────────────────────────────

func (e *Emitter) emitClass(c *ClassDecl) {
	// Collect @test methods
	for _, m := range c.Members {
		if md, ok := m.(*MethodDecl); ok {
			for _, ann := range md.Annotations {
				if ann.Name.Lexeme == "test" {
					e.testMethods = append(e.testMethods,
						fmt.Sprintf("%s::%s", c.Name.Lexeme, md.Name.Lexeme))
				}
			}
		}
	}

	e.writeIndent()
	if c.IsSealed {
		e.writef("// sealed\n")
		e.writeIndent()
	}
	if c.IsAbstract {
		e.writef("// abstract class %s", c.Name.Lexeme)
	} else {
		e.writef("class %s", c.Name.Lexeme)
	}
	if len(c.TypeParams) > 0 {
		// emit template declaration before class
	}
	if len(c.BaseTypes) > 0 {
		e.write(" : ")
		bases := make([]string, len(c.BaseTypes))
		for i, bt := range c.BaseTypes {
			bases[i] = "public " + e.typeNodeStr(bt)
		}
		e.write(strings.Join(bases, ", "))
	}
	e.write(" {\n")
	e.indent++

	// Separate members by access
	publics, privates, protecteds := e.partitionMembers(c.Members)

	if len(publics) > 0 {
		e.indent--
		e.writeln("public:")
		e.indent++
		for _, m := range publics {
			e.emitMember(m, c.Name.Lexeme)
		}
	}
	if len(protecteds) > 0 {
		e.indent--
		e.writeln("protected:")
		e.indent++
		for _, m := range protecteds {
			e.emitMember(m, c.Name.Lexeme)
		}
	}
	if len(privates) > 0 {
		e.indent--
		e.writeln("private:")
		e.indent++
		for _, m := range privates {
			e.emitMember(m, c.Name.Lexeme)
		}
	}

	e.indent--
	e.writeln("};")
	e.writeln("")
}

func (e *Emitter) partitionMembers(members []Decl) (pub, priv, prot []Decl) {
	for _, m := range members {
		acc := ACCESS_DEFAULT
		switch v := m.(type) {
		case *FieldDecl:
			acc = v.Access
		case *MethodDecl:
			acc = v.Access
		case *ConstructorDecl:
			acc = v.Access
		case *PropertyDecl:
			acc = v.Access
		case *DestructorDecl:
			acc = ACCESS_PUBLIC
		case *ClassDecl:
			acc = v.Access
		case *StructDecl:
			acc = v.Access
		case *EnumDecl:
			acc = v.Access
		}
		switch acc {
		case ACCESS_PROTECTED:
			prot = append(prot, m)
		case ACCESS_PRIVATE:
			priv = append(priv, m)
		default:
			pub = append(pub, m)
		}
	}
	return
}

func (e *Emitter) emitStruct(s *StructDecl) {
	e.writeIndent()
	e.writef("struct %s", s.Name.Lexeme)
	if len(s.BaseTypes) > 0 {
		e.write(" : ")
		bases := make([]string, len(s.BaseTypes))
		for i, bt := range s.BaseTypes {
			bases[i] = "public " + e.typeNodeStr(bt)
		}
		e.write(strings.Join(bases, ", "))
	}
	e.write(" {\n")
	e.indent++
	for _, m := range s.Members {
		e.emitMember(m, s.Name.Lexeme)
	}
	e.indent--
	e.writeln("};")
	e.writeln("")
}

func (e *Emitter) emitInterface(i *InterfaceDecl) {
	e.writeIndent()
	e.writef("class %s", i.Name.Lexeme)
	if len(i.BaseTypes) > 0 {
		e.write(" : ")
		bases := make([]string, len(i.BaseTypes))
		for idx, bt := range i.BaseTypes {
			bases[idx] = "public " + e.typeNodeStr(bt)
		}
		e.write(strings.Join(bases, ", "))
	}
	e.write(" {\n")
	e.writeln("public:")
	e.indent++
	e.writeln("virtual ~" + i.Name.Lexeme + "() = default;")
	for _, m := range i.Members {
		if md, ok := m.(*MethodDecl); ok {
			e.writeIndent()
			e.writef("virtual %s %s(%s) = 0;\n",
				e.typeNodeStr(md.ReturnType),
				md.Name.Lexeme,
				e.paramsStr(md.Params))
		}
	}
	e.indent--
	e.writeln("};")
	e.writeln("")
}

func (e *Emitter) emitEnum(en *EnumDecl) {
	baseType := "int"
	if en.BaseType != nil {
		baseType = e.typeNodeStr(en.BaseType)
	}
	e.writeIndent()
	e.writef("enum class %s : %s {\n", en.Name.Lexeme, baseType)
	e.indent++
	for i, m := range en.Members {
		e.writeIndent()
		if m.Value != nil {
			e.writef("%s = %s", m.Name.Lexeme, e.exprStr(m.Value))
		} else {
			e.write(m.Name.Lexeme)
		}
		if i < len(en.Members)-1 {
			e.write(",")
		}
		e.write("\n")
	}
	e.indent--
	e.writeln("};")
	e.writeln("")
}

// ── Member emission ───────────────────────────────────────────────────────────

func (e *Emitter) emitMember(d Decl, className string) {
	switch v := d.(type) {
	case *FieldDecl:
		e.emitField(v)
	case *MethodDecl:
		e.emitMethod(v, className)
	case *ConstructorDecl:
		e.emitConstructor(v, className)
	case *DestructorDecl:
		e.emitDestructor(v, className)
	case *PropertyDecl:
		e.emitProperty(v)
	case *ClassDecl:
		e.emitClass(v)
	case *StructDecl:
		e.emitStruct(v)
	case *EnumDecl:
		e.emitEnum(v)
	}
}

func (e *Emitter) emitField(f *FieldDecl) {
	e.writeIndent()
	if f.IsStatic {
		e.write("static ")
	}
	if f.IsConst {
		e.write("const ")
	}
	if f.IsReadonly {
		e.write("const ") // closest C++ equivalent
	}
	e.writef("%s %s", e.typeNodeStr(f.Type), f.Name.Lexeme)
	if f.Init != nil {
		e.writef(" = %s", e.exprStr(f.Init))
	}
	e.writeln(";")
}

func (e *Emitter) emitTopField(f *FieldDecl) {
	e.emitField(f)
}

func (e *Emitter) emitMethod(m *MethodDecl, className string) {
	e.writeIndent()
	// template
	if len(m.TypeParams) > 0 {
		params := make([]string, len(m.TypeParams))
		for i, p := range m.TypeParams {
			params[i] = "typename " + p.Lexeme
		}
		e.writef("template<%s>\n", strings.Join(params, ", "))
		e.writeIndent()
	}
	if m.IsStatic {
		e.write("static ")
	}
	if m.IsVirtual || m.IsAbstract {
		e.write("virtual ")
	}
	if m.IsOverride && !m.IsVirtual {
		e.write("virtual ")
	}
	e.writef("%s %s(%s)",
		e.typeNodeStr(m.ReturnType),
		m.Name.Lexeme,
		e.paramsStr(m.Params))
	if m.IsOverride {
		e.write(" override")
	}
	if m.IsAbstract {
		e.writeln(" = 0;")
		return
	}
	if m.IsExtern {
		e.writeln(";")
		return
	}
	if m.Body == nil {
		e.writeln(";")
		return
	}
	e.write(" ")
	e.emitBlock(m.Body)
	e.writeln("")
}

func (e *Emitter) emitTopMethod(m *MethodDecl) {
	e.emitMethod(m, "")
}

func (e *Emitter) emitConstructor(c *ConstructorDecl, className string) {
	e.writeIndent()
	e.writef("%s(%s)", className, e.paramsStr(c.Params))
	if len(c.BaseArgs) > 0 {
		args := make([]string, len(c.BaseArgs))
		for i, a := range c.BaseArgs {
			args[i] = e.exprStr(a)
		}
		e.writef(" : %s(%s)", className, strings.Join(args, ", "))
		// actually we should use the parent class name here but we don't have it
	}
	e.write(" ")
	e.emitBlock(c.Body)
	e.writeln("")
}

func (e *Emitter) emitDestructor(d *DestructorDecl, className string) {
	e.writeIndent()
	e.writef("virtual ~%s() ", className)
	e.emitBlock(d.Body)
	e.writeln("")
}

func (e *Emitter) emitProperty(p *PropertyDecl) {
	typStr := e.typeNodeStr(p.Type)
	// Backing field for auto-properties
	hasAutoGet := p.Getter != nil && p.Getter.Body == nil
	hasAutoSet := p.Setter != nil && p.Setter.Body == nil
	if hasAutoGet || hasAutoSet {
		e.writeIndent()
		e.writef("%s _%s{};\n", typStr, p.Name.Lexeme)
	}

	// Getter
	if p.Getter != nil {
		e.writeIndent()
		e.writef("%s get_%s()", typStr, p.Name.Lexeme)
		if p.Getter.Body == nil {
			e.writef(" { return _%s; }\n", p.Name.Lexeme)
		} else {
			e.write(" ")
			e.emitBlock(p.Getter.Body)
			e.writeln("")
		}
	}
	// Setter
	if p.Setter != nil {
		e.writeIndent()
		e.writef("void set_%s(%s value)", p.Name.Lexeme, typStr)
		if p.Setter.Body == nil {
			e.writef(" { _%s = value; }\n", p.Name.Lexeme)
		} else {
			e.write(" ")
			e.emitBlock(p.Setter.Body)
			e.writeln("")
		}
	}
}

// ── Statement emission ────────────────────────────────────────────────────────

func (e *Emitter) emitBlock(b *Block) {
	e.write("{\n")
	e.indent++
	for _, s := range b.Stmts {
		e.emitStmt(s)
	}
	e.indent--
	e.writeIndent()
	e.write("}")
}

func (e *Emitter) emitStmt(s Stmt) {
	switch v := s.(type) {
	case *Block:
		e.writeIndent()
		e.emitBlock(v)
		e.writeln("")
	case *ExprStmt:
		e.writeIndent()
		e.writef("%s;\n", e.exprStr(v.Expr))
	case *ReturnStmt:
		e.writeIndent()
		if v.Value != nil {
			e.writef("return %s;\n", e.exprStr(v.Value))
		} else {
			e.writeln("return;")
		}
	case *LocalVarDecl:
		e.emitLocalVar(v)
	case *IfStmt:
		e.emitIf(v)
	case *WhileStmt:
		e.writeIndent()
		e.writef("while (%s) ", e.exprStr(v.Cond))
		e.emitBlockOrStmt(v.Body)
	case *DoWhileStmt:
		e.writeIndent()
		e.write("do ")
		e.emitBlockOrStmt(v.Body)
		e.writef(" while (%s);\n", e.exprStr(v.Cond))
	case *ForStmt:
		e.emitFor(v)
	case *ForeachStmt:
		e.emitForeach(v)
	case *SwitchStmt:
		e.emitSwitch(v)
	case *BreakStmt:
		e.writeIndent()
		e.writeln("break;")
	case *ContinueStmt:
		e.writeIndent()
		e.writeln("continue;")
	case *ThrowStmt:
		e.writeIndent()
		e.writef("throw %s;\n", e.exprStr(v.Expr))
	case *TryCatchStmt:
		e.emitTryCatch(v)
	}
}

func (e *Emitter) emitLocalVar(v *LocalVarDecl) {
	e.writeIndent()
	if v.IsConst {
		e.write("const ")
	}
	if v.TypeNode != nil {
		e.writef("%s %s", e.typeNodeStr(v.TypeNode), v.Name.Lexeme)
	} else {
		// var — use auto
		e.writef("auto %s", v.Name.Lexeme)
	}
	if v.Init != nil {
		e.writef(" = %s", e.exprStr(v.Init))
	}
	e.writeln(";")
}

func (e *Emitter) emitIf(i *IfStmt) {
	e.writeIndent()
	e.writef("if (%s) ", e.exprStr(i.Cond))
	e.emitBlockOrStmt(i.Then)
	if i.Else != nil {
		e.write(" else ")
		if _, ok := i.Else.(*IfStmt); ok {
			// else if — no extra newline
			e.emitStmtInline(i.Else)
		} else {
			e.emitBlockOrStmt(i.Else)
			e.writeln("")
		}
	} else {
		e.writeln("")
	}
}

func (e *Emitter) emitStmtInline(s Stmt) {
	// emit without leading indent (already written)
	switch v := s.(type) {
	case *IfStmt:
		e.writef("if (%s) ", e.exprStr(v.Cond))
		e.emitBlockOrStmt(v.Then)
		if v.Else != nil {
			e.write(" else ")
			e.emitStmtInline(v.Else)
		} else {
			e.writeln("")
		}
	default:
		e.emitBlockOrStmt(s)
		e.writeln("")
	}
}

func (e *Emitter) emitBlockOrStmt(s Stmt) {
	if b, ok := s.(*Block); ok {
		e.emitBlock(b)
	} else {
		e.write("{\n")
		e.indent++
		e.emitStmt(s)
		e.indent--
		e.writeIndent()
		e.write("}")
	}
}

func (e *Emitter) emitFor(f *ForStmt) {
	e.writeIndent()
	e.write("for (")
	if f.Init != nil {
		switch iv := f.Init.(type) {
		case *LocalVarDecl:
			if iv.IsConst {
				e.write("const ")
			}
			if iv.TypeNode != nil {
				e.writef("%s %s", e.typeNodeStr(iv.TypeNode), iv.Name.Lexeme)
			} else {
				e.writef("auto %s", iv.Name.Lexeme)
			}
			if iv.Init != nil {
				e.writef(" = %s", e.exprStr(iv.Init))
			}
		case *ExprStmt:
			e.write(e.exprStr(iv.Expr))
		}
	}
	e.write("; ")
	if f.Cond != nil {
		e.write(e.exprStr(f.Cond))
	}
	e.write("; ")
	posts := make([]string, len(f.Post))
	for i, p := range f.Post {
		posts[i] = e.exprStr(p)
	}
	e.write(strings.Join(posts, ", "))
	e.write(") ")
	e.emitBlockOrStmt(f.Body)
	e.writeln("")
}

func (e *Emitter) emitForeach(f *ForeachStmt) {
	e.writeIndent()
	e.writef("for (auto& %s : %s) ",
		f.ElemName.Lexeme, e.exprStr(f.Range))
	e.emitBlockOrStmt(f.Body)
	e.writeln("")
}

func (e *Emitter) emitSwitch(s *SwitchStmt) {
	e.writeIndent()
	e.writef("switch (%s) {\n", e.exprStr(s.Expr))
	for _, c := range s.Cases {
		if c.Value == nil {
			e.writeIndent()
			e.writeln("default:")
		} else {
			e.writeIndent()
			e.writef("case %s:\n", e.exprStr(c.Value))
		}
		e.indent++
		for _, st := range c.Body {
			e.emitStmt(st)
		}
		e.indent--
	}
	e.writeIndent()
	e.writeln("}")
}

func (e *Emitter) emitTryCatch(t *TryCatchStmt) {
	e.writeIndent()
	e.write("try ")
	e.emitBlock(t.Body)
	for _, c := range t.Catches {
		e.write(" catch (")
		if c.ExcType != nil {
			e.writef("%s", e.typeNodeStr(c.ExcType))
			if c.ExcName.Lexeme != "" {
				e.writef("& %s", c.ExcName.Lexeme)
			}
		} else {
			e.write("...")
		}
		e.write(") ")
		e.emitBlock(c.Body)
	}
	if t.Finally != nil {
		// C++ has no finally, wrap in RAII struct
		e.write("\n")
		e.writeIndent()
		e.writeln("// finally block (executed after try/catch)")
		e.writeIndent()
		e.emitBlock(t.Finally)
	}
	e.writeln("")
}

// ── Expression emission ───────────────────────────────────────────────────────

func (e *Emitter) exprStr(expr Expr) string {
	if expr == nil {
		return ""
	}
	switch v := expr.(type) {
	case *IntLit:
		return fmt.Sprintf("%d", v.Val)
	case *FloatLit:
		return fmt.Sprintf("%gf", v.Val)
	case *DoubleLit:
		return fmt.Sprintf("%g", v.Val)
	case *StringLit:
		return fmt.Sprintf("std::string(%q)", v.Val)
	case *CharLit:
		if v.Val == '\'' {
			return "'\\''"
		}
		return fmt.Sprintf("'%c'", v.Val)
	case *BoolLit:
		if v.Val {
			return "true"
		}
		return "false"
	case *NullLit:
		return "nullptr"
	case *IdentExpr:
		return e.mapIdent(v.Tok.Lexeme)
	case *ThisExpr:
		return "this"
	case *BaseExpr:
		return "/* base */"
	case *BinaryExpr:
		return fmt.Sprintf("(%s %s %s)",
			e.exprStr(v.Left), v.Op.Lexeme, e.exprStr(v.Right))
	case *UnaryExpr:
		if v.IsPost {
			return fmt.Sprintf("(%s%s)", e.exprStr(v.Operand), v.Op.Lexeme)
		}
		return fmt.Sprintf("(%s%s)", v.Op.Lexeme, e.exprStr(v.Operand))
	case *AssignExpr:
		op := v.Op.Lexeme
		if op == "??=" {
			// x ??= y  ->  if (!x) x = y; (simplified)
			return fmt.Sprintf("(%s = (%s) ? (%s) : (%s))",
				e.exprStr(v.Target), e.exprStr(v.Target),
				e.exprStr(v.Target), e.exprStr(v.Value))
		}
		return fmt.Sprintf("(%s %s %s)",
			e.exprStr(v.Target), op, e.exprStr(v.Value))
	case *TernaryExpr:
		return fmt.Sprintf("(%s ? %s : %s)",
			e.exprStr(v.Cond), e.exprStr(v.Then), e.exprStr(v.Else))
	case *CallExpr:
		return e.emitCall(v)
	case *MemberExpr:
		obj := e.exprStr(v.Object)
		return fmt.Sprintf("%s.%s", obj, v.Member.Lexeme)
	case *IndexExpr:
		return fmt.Sprintf("%s[%s]", e.exprStr(v.Object), e.exprStr(v.Index))
	case *NewExpr:
		args := make([]string, len(v.Args))
		for i, a := range v.Args {
			args[i] = e.exprStr(a)
		}
		typStr := e.typeNodeStr(v.Type)
		return fmt.Sprintf("%s(%s)", typStr, strings.Join(args, ", "))
	case *NewArrayExpr:
		elem := e.typeNodeStr(v.ElemType)
		if len(v.Init) > 0 {
			elems := make([]string, len(v.Init))
			for i, el := range v.Init {
				elems[i] = e.exprStr(el)
			}
			return fmt.Sprintf("std::vector<%s>{%s}", elem, strings.Join(elems, ", "))
		}
		if v.Size != nil {
			return fmt.Sprintf("std::vector<%s>(%s)", elem, e.exprStr(v.Size))
		}
		return fmt.Sprintf("std::vector<%s>{}", elem)
	case *CastExpr:
		return fmt.Sprintf("static_cast<%s>(%s)",
			e.typeNodeStr(v.Type), e.exprStr(v.Expr))
	case *IsExpr:
		return fmt.Sprintf("(dynamic_cast<%s*>(&%s) != nullptr)",
			e.typeNodeStr(v.Type), e.exprStr(v.Expr))
	case *AsExpr:
		return fmt.Sprintf("dynamic_cast<%s*>(%s)",
			e.typeNodeStr(v.Type), e.exprStr(v.Expr))
	case *TypeofExpr:
		return fmt.Sprintf("std::string(typeid(%s).name())", e.typeNodeStr(v.Type))
	case *NullCoalExpr:
		left := e.exprStr(v.Left)
		right := e.exprStr(v.Right)
		return fmt.Sprintf("((%s) != nullptr ? (%s) : (%s))", left, left, right)
	case *ArrayInitExpr:
		elems := make([]string, len(v.Elems))
		for i, el := range v.Elems {
			elems[i] = e.exprStr(el)
		}
		return "{" + strings.Join(elems, ", ") + "}"
	}
	return "/* unknown_expr */"
}

func (e *Emitter) emitCall(c *CallExpr) string {
	callee := e.exprStr(c.Callee)
	args := make([]string, len(c.Args))
	for i, a := range c.Args {
		args[i] = e.exprStr(a)
	}

	// Map common C# methods to C++
	switch callee {
	case "Console.WriteLine":
		return fmt.Sprintf("std::cout << %s << std::endl", strings.Join(args, " << "))
	case "Console.Write":
		return fmt.Sprintf("std::cout << %s", strings.Join(args, " << "))
	case "Console.ReadLine":
		return "[]() { std::string _s; std::getline(std::cin, _s); return _s; }()"
	case "int.Parse", "Int32.Parse":
		return fmt.Sprintf("std::stoi(%s)", strings.Join(args, ", "))
	case "long.Parse", "Int64.Parse":
		return fmt.Sprintf("std::stoll(%s)", strings.Join(args, ", "))
	case "double.Parse", "Double.Parse":
		return fmt.Sprintf("std::stod(%s)", strings.Join(args, ", "))
	case "float.Parse", "Single.Parse":
		return fmt.Sprintf("std::stof(%s)", strings.Join(args, ", "))
	case "bool.Parse":
		return fmt.Sprintf("(std::string(%s) == \"true\")", strings.Join(args, ""))
	case "string.IsNullOrEmpty", "String.IsNullOrEmpty":
		return fmt.Sprintf("(%s.empty())", strings.Join(args, ""))
	case "string.IsNullOrWhiteSpace", "String.IsNullOrWhiteSpace":
		return fmt.Sprintf("(%s.find_first_not_of(\" \\t\\n\\r\") == std::string::npos)", strings.Join(args, ""))
	case "Math.Abs":
		return fmt.Sprintf("std::abs(%s)", strings.Join(args, ", "))
	case "Math.Max":
		return fmt.Sprintf("std::max(%s)", strings.Join(args, ", "))
	case "Math.Min":
		return fmt.Sprintf("std::min(%s)", strings.Join(args, ", "))
	case "Math.Sqrt":
		return fmt.Sprintf("std::sqrt(%s)", strings.Join(args, ", "))
	case "Math.Pow":
		return fmt.Sprintf("std::pow(%s)", strings.Join(args, ", "))
	case "Math.Floor":
		return fmt.Sprintf("std::floor(%s)", strings.Join(args, ", "))
	case "Math.Ceiling":
		return fmt.Sprintf("std::ceil(%s)", strings.Join(args, ", "))
	case "Math.Round":
		return fmt.Sprintf("std::round(%s)", strings.Join(args, ", "))
	case "typeof":
		if len(args) > 0 {
			return fmt.Sprintf("std::string(typeid(%s).name())", args[0])
		}
		return "std::string()"
	}

	// Method on an object: check for .ToString(), .Length etc
	if strings.HasSuffix(callee, ".ToString") {
		obj := strings.TrimSuffix(callee, ".ToString")
		return fmt.Sprintf("std::to_string(%s)", obj)
	}
	if strings.HasSuffix(callee, ".Length") || strings.HasSuffix(callee, ".Count") {
		obj := strings.TrimSuffix(strings.TrimSuffix(callee, ".Length"), ".Count")
		return fmt.Sprintf("%s.size()", obj)
	}
	if strings.HasSuffix(callee, ".Add") {
		obj := strings.TrimSuffix(callee, ".Add")
		return fmt.Sprintf("%s.push_back(%s)", obj, strings.Join(args, ", "))
	}
	if strings.HasSuffix(callee, ".Contains") {
		obj := strings.TrimSuffix(callee, ".Contains")
		return fmt.Sprintf("(std::find(%s.begin(), %s.end(), %s) != %s.end())",
			obj, obj, strings.Join(args, ", "), obj)
	}
	if strings.HasSuffix(callee, ".Remove") {
		obj := strings.TrimSuffix(callee, ".Remove")
		return fmt.Sprintf("%s.erase(std::remove(%s.begin(), %s.end(), %s), %s.end())",
			obj, obj, obj, strings.Join(args, ", "), obj)
	}

	return fmt.Sprintf("%s(%s)", callee, strings.Join(args, ", "))
}

func (e *Emitter) mapIdent(name string) string {
	switch name {
	case "string":
		return "std::string"
	case "object":
		return "void*"
	case "bool":
		return "bool"
	case "int":
		return "int32_t"
	case "uint":
		return "uint32_t"
	case "long":
		return "int64_t"
	case "ulong":
		return "uint64_t"
	case "short":
		return "int16_t"
	case "ushort":
		return "uint16_t"
	case "byte":
		return "uint8_t"
	case "sbyte":
		return "int8_t"
	case "float":
		return "float"
	case "double":
		return "double"
	case "char":
		return "char"
	case "true":
		return "true"
	case "false":
		return "false"
	case "null":
		return "nullptr"
	}
	return name
}

// ── Type node → C++ type string ───────────────────────────────────────────────

func (e *Emitter) typeNodeStr(tn *TypeNode) string {
	if tn == nil {
		return "void"
	}
	base := e.mapCsType(tn.Tok.Lexeme)
	if len(tn.Generic) > 0 {
		args := make([]string, len(tn.Generic))
		for i, g := range tn.Generic {
			args[i] = e.typeNodeStr(g)
		}
		switch tn.Tok.Lexeme {
		case "List":
			return fmt.Sprintf("std::vector<%s>", strings.Join(args, ", "))
		case "Dictionary":
			return fmt.Sprintf("std::unordered_map<%s>", strings.Join(args, ", "))
		case "Queue":
			return fmt.Sprintf("std::queue<%s>", strings.Join(args, ", "))
		case "Stack":
			return fmt.Sprintf("std::stack<%s>", strings.Join(args, ", "))
		case "HashSet":
			return fmt.Sprintf("std::unordered_set<%s>", strings.Join(args, ", "))
		case "IEnumerable", "IList", "ICollection":
			return fmt.Sprintf("std::vector<%s>", strings.Join(args, ", "))
		default:
			return fmt.Sprintf("%s<%s>", base, strings.Join(args, ", "))
		}
	}
	if tn.IsArray {
		return fmt.Sprintf("std::vector<%s>", base)
	}
	if tn.IsNullable {
		// Use pointer for nullable value types
		return fmt.Sprintf("%s*", base)
	}
	return base
}

func (e *Emitter) mapCsType(name string) string {
	switch name {
	case "void":
		return "void"
	case "int":
		return "int32_t"
	case "uint":
		return "uint32_t"
	case "long":
		return "int64_t"
	case "ulong":
		return "uint64_t"
	case "short":
		return "int16_t"
	case "ushort":
		return "uint16_t"
	case "byte":
		return "uint8_t"
	case "sbyte":
		return "int8_t"
	case "float":
		return "float"
	case "double":
		return "double"
	case "bool":
		return "bool"
	case "char":
		return "char"
	case "string", "String":
		return "std::string"
	case "object", "Object":
		return "void*"
	case "decimal":
		return "double" // approximation
	}
	return name
}

func (e *Emitter) paramsStr(params []*Param) string {
	parts := make([]string, len(params))
	for i, p := range params {
		prefix := ""
		if p.Modifier.Lexeme == "ref" || p.Modifier.Lexeme == "out" {
			prefix = "&"
		} else if p.Modifier.Lexeme == "params" {
			// variadic — use vector
			parts[i] = fmt.Sprintf("std::vector<%s> %s", e.typeNodeStr(p.Type), p.Name.Lexeme)
			continue
		}
		parts[i] = fmt.Sprintf("%s%s %s", e.typeNodeStr(p.Type), prefix, p.Name.Lexeme)
		if p.Default != nil {
			parts[i] += " = " + e.exprStr(p.Default)
		}
	}
	return strings.Join(parts, ", ")
}

// ── Helpers ───────────────────────────────────────────────────────────────────

func (e *Emitter) write(s string)                    { e.sb.WriteString(s) }
func (e *Emitter) writeln(s string)                  { e.sb.WriteString(e.indentStr() + s + "\n") }
func (e *Emitter) writef(f string, a ...interface{}) { e.sb.WriteString(fmt.Sprintf(f, a...)) }
func (e *Emitter) writeIndent()                      { e.sb.WriteString(e.indentStr()) }
func (e *Emitter) indentStr() string                 { return strings.Repeat("    ", e.indent) }

func (e *Emitter) GetTestMethods() []string { return e.testMethods }
